# Generated by Django 5.1.1 on 2024-10-09 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('swimmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('year', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('front_force', models.JSONField()),
                ('back_force', models.JSONField()),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.swimmer')),
            ],
        ),
    ]
