# Generated by Django 5.1.2 on 2024-10-30 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyRio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_force', models.FloatField(default=0.0)),
                ('front_force', models.FloatField(default=0.0)),
                ('back_force', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('swimmer_name', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('year', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('start_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_force', models.JSONField()),
                ('front_force', models.JSONField()),
                ('back_force', models.JSONField()),
                ('swimmer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.swimmer')),
            ],
        ),
    ]
