# Generated by Django 4.2.16 on 2024-11-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='start_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
