# Generated by Django 4.2.16 on 2024-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_myrio_back_force_alter_myrio_front_force_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrio',
            name='back_force',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='myrio',
            name='front_force',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='myrio',
            name='total_force',
            field=models.FloatField(default=0.0),
        ),
    ]
